language: python
python:
  - "3.5"
sudo: false
env:
  matrix:
    - TOXENV=pep8
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=py35
install:
  - pip install tox
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls
notifications:
    email:
        on_success: change
        on_failure: always
