
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '710A5033EDB95032EF88D74304132DE5'
    
_lr_action_items = {'NUMBER':([0,5,],[1,6,]),'$end':([0,1,2,3,4,6,7,],[-1,-4,-2,0,-3,-6,-5,]),'IDENTIFIER':([0,5,],[4,7,]),'DOT':([1,2,4,6,7,],[-4,5,-3,-6,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'path':([0,],[2,]),'scope':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> scope","S'",1,None,None,None),
  ('scope -> <empty>','scope',0,'p_scope_empty','yacc.py',11),
  ('scope -> path','scope',1,'p_scope_path','yacc.py',16),
  ('path -> IDENTIFIER','path',1,'p_path','yacc.py',22),
  ('path -> NUMBER','path',1,'p_path','yacc.py',23),
  ('path -> path DOT IDENTIFIER','path',3,'p_dotted_path','yacc.py',30),
  ('path -> path DOT NUMBER','path',3,'p_dotted_path','yacc.py',31),
]
